/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomBar: typeof import('./src/components/bottomBar.vue')['default']
    CallFormDialog: typeof import('./src/components/callLogsManagement/CallFormDialog.vue')['default']
    CallViewDialog: typeof import('./src/components/callLogsManagement/CallViewDialog.vue')['default']
    Dialog: typeof import('./src/components/callLogsManagement/dialog.vue')['default']
    DialogView: typeof import('./src/components/callLogsManagement/dialogView.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMessage: typeof import('element-plus/es')['ElMessage']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Filter: typeof import('./src/components/ticketManagement/filter.vue')['default']
    FilterBar: typeof import('./src/components/ticketManagement/FilterBar.vue')['default']
    ModalSearch: typeof import('./src/components/ModalSearch.vue')['default']
    Paginate: typeof import('./src/components/Paginate.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    RdpTable: typeof import('./src/components/rdpTable.vue')['default']
    RdpTableItem: typeof import('./src/components/rdpTableItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    State: typeof import('./src/components/callLogsManagement/state.vue')['default']
    Table: typeof import('./src/components/table.vue')['default']
    TicketHeader: typeof import('./src/components/ticketManagement/TicketHeader.vue')['default']
    TicketStats: typeof import('./src/components/ticketManagement/TicketStats.vue')['default']
    TopBar: typeof import('./src/components/topBar.vue')['default']
  }
}
